// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBd4yy70aN00d-_BWdiy4rApAEFFnMDIc',
    appId: '1:1082537821939:web:629476a161e48017df5986',
    messagingSenderId: '1082537821939',
    projectId: 'chat-app-a7b3b',
    authDomain: 'chat-app-a7b3b.firebaseapp.com',
    storageBucket: 'chat-app-a7b3b.firebasestorage.app',
    measurementId: 'G-Q4D4YBRJ50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtv796FPqsk3jaF2DNxj2xuMOgcKY9ank',
    appId: '1:1082537821939:android:6abc8044190ec3d6df5986',
    messagingSenderId: '1082537821939',
    projectId: 'chat-app-a7b3b',
    storageBucket: 'chat-app-a7b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9dqxJPQzrWY_H9XN-m7wX5ifDszY_kbo',
    appId: '1:1082537821939:ios:2ad1996807cb1199df5986',
    messagingSenderId: '1082537821939',
    projectId: 'chat-app-a7b3b',
    storageBucket: 'chat-app-a7b3b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9dqxJPQzrWY_H9XN-m7wX5ifDszY_kbo',
    appId: '1:1082537821939:ios:2ad1996807cb1199df5986',
    messagingSenderId: '1082537821939',
    projectId: 'chat-app-a7b3b',
    storageBucket: 'chat-app-a7b3b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBd4yy70aN00d-_BWdiy4rApAEFFnMDIc',
    appId: '1:1082537821939:web:9fd3245df6dd1a56df5986',
    messagingSenderId: '1082537821939',
    projectId: 'chat-app-a7b3b',
    authDomain: 'chat-app-a7b3b.firebaseapp.com',
    storageBucket: 'chat-app-a7b3b.firebasestorage.app',
    measurementId: 'G-J008QJ7HYC',
  );
}
